argument parsing added

diff --git a/renderGraph b/renderGraph
--- a/renderGraph
+++ b/renderGraph
@@ -1,30 +1,112 @@
 #!/bin/bash
 
-USAGE=`basename "$0"`" [ASCII GRAPH FILE] [FONT NAME]"
-DESCRIPTION="Reads a graph from ascii drawing and creates png file using image magic convert command."
-
-if [[ "$#" -lt 1 || "$1" == "--help" ]]; then
-	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
-fi
+USAGE=`basename "$0"`" [OPTION]... [GRAPH TEXT FILE]"
+DESCRIPTION="Reads a graph from ascii drawing and creates png file using image magick convert command.\
+	-s, --size=SIZE\
+		set height of one cell in pixels\
+\
+	-t, --tab-width=SIZE\
+		set to how many spaces tabs in input file are gonna be converted\
+\
+	-c, --no-color\
+		do not colorize the labels of the graph\
+\
+	-h, --help\
+		display this help and exit\
+\
+	-v, --version\
+		output version information and exit\n"
+HOMEPAGE_BUGS="https://github.com/gto76/ascii-git-graph-to-png/issues"
+AUTHOR="Jure Sorn"
+COPYRIGHT="Copyright (c) 2014 Jure Sorn. The MIT License (MIT)."
+VERSION="v0.9.0"
 
 #############
 DEBUG="false" 
 #############
 
-#######################################
-SIZEY=${2:-"60"} # How tall is one cell
-TAB_WIDTH=4
-COLOR="true"
-FONT=${4:-"DejaVu-Sans-Mono-Bold-Oblique"}
-NODE_FONT=${3:-"Liberation-Mono-Bold"}
-#######################################
+#####################################################################
+SIZEY="60" # How tall is one cell.
+TAB_WIDTH="4" # Need to be set correctly if input file contains tabs.
+COLOR="true" # Colorize the labels using standard git colors.
+PRINT_HELP="false"
+PRINT_VERSION="false"
+#####################################################################
 
+#########################
+#### PARSE ARGUMENTS ####
+#########################
+parseArguments() {
+	# read the options
+	TEMP=`getopt -o hvcs:t: --long version,help,no-color,size:,tab-width: -n 'test.sh' -- "$@"`
+	eval set -- "$TEMP"
+
+	# extract options and their arguments into variables.
+	while true ; do
+		case "$1" in
+			-h|--help) PRINT_HELP="true" ; shift ;;
+			-v|--version) PRINT_VERSION="true" ; shift ;;
+			-c|--no-color) COLOR="false" ; shift ;;
+			-s|--size)
+				case "$2" in
+					"") shift 2 ;;
+					*) SIZEY=$2 ; shift 2 ;;
+				esac ;;
+			-t|--tab-width)
+				case "$2" in
+					"") shift 2 ;;
+					*) TAB_WIDTH=$2 ; shift 2 ;;
+				esac ;;
+			--) shift ; break ;;
+			*) echo "Internal error!" ; exit 1 ;;
+		esac
+	done
+
+	shift $(expr $OPTIND - 1 )
+	FILE_NAME="$1"
+}
+
+##########################
+#### VERIFY ARGUMENTS #### 
+##########################
+
+verifyArguments() {
+	if [[ "$PRINT_HELP" == "true" ]]; then
+		echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION\n" 
+		echo -e "Report bugs to $HOMEPAGE_BUGS"  
+		echo -e "Written by $AUTHOR."; echo -e "$COPYRIGHT"
+		exit 0
+	elif [[ "$PRINT_VERSION" == "true" ]]; then
+		echo `basename "$0"` "$VERSION"
+		exit 0
+	elif [[ -z "$FILE_NAME" ]]; then
+		echo "Filename was not specified." >&2
+		exit 1
+	elif [[ ! -r "$FILE_NAME" ]]; then
+		echo "File does not exist, or you don't have permission to read it" >&2
+		exit 1
+	elif [[ -z `cat "$SIZEY" | grep -p '^[0-9]+$'` ]]; then
+		echo "Invalid size" >&2
+		exit 1
+	elif [[ "$SIZEY" -lt 5 || "$SIZEY" -gt 200 ]]; then
+		echo "Size out of range, use values between 5 and 200" >&2
+		exit 1
+	elif [[ -z `cat "$TAB_WIDTH" | grep -p '^[0-9]+$'` ]]; then
+		echo "Invalid tab widht" >&2
+		exit 1
+	elif [[ "$TAB_WIDTH" -lt 1 || "$TAB_WIDTH" -gt 20 ]]; then
+		echo "Tab width out of range, use values between 1 and 20" >&2
+		exit 1
+	fi	
+}
 
 #######################
 #### SET CONSTANTS ####
 #######################
 
 setConstants() {
+	FONT="DejaVu-Sans-Mono-Bold-Oblique"
+	NODE_FONT="Liberation-Mono-Bold"
 	# Width of one ascii cell in pixels.
 	SIZEX=`echo "scale=1;$SIZEY*2/3" | bc | sed 's/\..*//'`
 	# Heigh of a font.
@@ -240,11 +322,15 @@ sortInstructions() {
 ####################
 
 createPng() {
+	strokeWidth=`echo "scale=1;$SIZEY/30" | bc`
+	echo "$strokeWidth"
+
 	echo -e "push graphic-context\n" > tmp.mvg
 	echo -e "viewbox 0 0 $canvasSizeX $canvasSizeY" >> tmp.mvg
 	echo -e "fill 'white'" >> tmp.mvg
 	echo -e "stroke 'black'" >> tmp.mvg
 	echo -e "stroke-antialias 1" >> tmp.mvg
+	echo -e "stroke-width $strokeWidth" >> tmp.mvg
 	#echo -e "stroke-width 2" >> tmp.mvg
 	echo -e "$drawingInstructions\n" >> tmp.mvg
 	echo -e "push graphic-context" >> tmp.mvg
@@ -264,8 +350,10 @@ createPng() {
 ##############
 
 main() {
+	parseArguments "$@"
+	verifyArguments
 	setConstants
-	copyLinesIntoArray "$1"
+	copyLinesIntoArray "$FILE_NAME"
 	calculateCanvasSize
 
 	# Drawing instructions for the imagemagic
