arguments tested

diff --git a/render-graph b/render-graph
--- a/render-graph
+++ b/render-graph
@@ -1,16 +1,28 @@
 #!/bin/bash
 
+#############
+DEBUG="false" 
+#############
+
+#####################################################################
+SIZEY="60" # How tall is one cell.
+TAB_WIDTH="4" # Need to be set correctly if input file contains tabs.
+COLOR="true" # Colorize the labels using standard git colors.
+PRINT_HELP="false"
+PRINT_VERSION="false"
+#####################################################################
+
 APP_NAME=`basename "$0"`
 USAGE="$APP_NAME [OPTION]... [FILE]"
 DESCRIPTION="Reads a graph from ascii drawing and creates PNG file using ImageMagick's 
 convert command. Intended for drawings of git history graphs.
 
 	-s, --size=SIZE
-		set height of one cell in pixels
+		set height of one cell in pixels, default value is $SIZEY
 
 	-t, --tab-width=SIZE
-		set to how many spaces tabs in input file are gonna be 
-		converted
+		set number of spaces tabs in input file are gonna be 
+		converted to, default value is $TAB_WIDTH
 
 	-c, --no-color
 		do not colorize the labels of the graph
@@ -24,18 +36,6 @@ HOMEPAGE_BUGS="https://github.com/gto76/ascii-git-graph-to-png/issues"
 AUTHOR="Jure Sorn"
 COPYRIGHT="Copyright (c) 2014 Jure Sorn. The MIT License (MIT)."
 VERSION="v0.9.0"
-
-#############
-DEBUG="false" 
-#############
-
-#####################################################################
-SIZEY="60" # How tall is one cell.
-TAB_WIDTH="4" # Need to be set correctly if input file contains tabs.
-COLOR="true" # Colorize the labels using standard git colors.
-PRINT_HELP="false"
-PRINT_VERSION="false"
-#####################################################################
 
 #########################
 #### PARSE ARGUMENTS ####
@@ -96,11 +96,11 @@ verifyArguments() {
 	elif [[ -z `echo "$SIZEY" | grep -P '^[0-9]+$'` ]]; then
 		echo "$APP_NAME: Invalid size argument" >&2
 		exit 1
-	elif [[ "$SIZEY" -lt 5 || "$SIZEY" -gt 200 ]]; then
-		echo "$APP_NAME: Size argument is out of range, use values between 5 and 200" >&2
+	elif [[ "$SIZEY" -lt 2 || "$SIZEY" -gt 200 ]]; then
+		echo "$APP_NAME: Size argument is out of range, use values between 2 and 200" >&2
 		exit 1
 	elif [[ -z `echo "$TAB_WIDTH" | grep -P '^[0-9]+$'` ]]; then
-		echo "$APP_NAME: Invalid tab widht" >&2
+		echo "$APP_NAME: Invalid tab width" >&2
 		exit 1
 	elif [[ "$TAB_WIDTH" -lt 1 || "$TAB_WIDTH" -gt 20 ]]; then
 		echo "$APP_NAME: Tab width out of range, use values between 1 and 20" >&2
@@ -117,7 +117,7 @@ setConstants() {
 	NODE_FONT="Liberation-Mono-Bold"
 	# Width of one ascii cell in pixels.
 	SIZEX=`echo "scale=1;$SIZEY*2/3" | bc | sed 's/^\./0\./' | sed 's/\..*//'`
-	# Heigh of a font.
+	# Height of a font.
 	let FONT_SIZE=("$SIZEY"*3)/4
 	# Distance from rectangles edge to the edge of the cell in the pixels.
 	let RECTANGLE_OFFSET="$SIZEX"/8
@@ -129,7 +129,6 @@ setConstants() {
 	VERTICAL_LIFT=`echo "$VERTICAL_LIFT_EXPRESSION" | bc | sed 's/^\./0\./' | sed 's/\..*//'`
 	let RECTANGLE_HEIGHT="$SIZEY"-2*"$RECTANGLE_OFFSET"
 	# How far from the upper cells will be texts bottom.
-	#let TEXT_OFFSET_Y=("$RECTANGLE_HEIGHT"-"$FONT_SIZE")/2+"$RECTANGLE_OFFSET"+"$FONT_SIZE"-"$VERTICAL_LIFT"
 	TEXT_OFFSET_Y_EXPRESSION="scale=1;($RECTANGLE_HEIGHT-$FONT_SIZE)/2+$RECTANGLE_OFFSET+$FONT_SIZE-$VERTICAL_LIFT"
 	TEXT_OFFSET_Y=`echo "$TEXT_OFFSET_Y_EXPRESSION" | bc | sed 's/^\./0\./' | sed 's/\..*//'`
 	# Width of the lines in pixels.
@@ -177,7 +176,7 @@ setColor() {
 	elif [[ -n `echo "$1" | grep -i '^head'` ]]; then
 		color="rgb(52, 226, 226)" #HEAD -> aqua
 	elif [[ -n `echo "$1" | grep -i '^v[0-9]\|^[0-9]'` ]]; then
-		color="rgb(252, 233, 77)" #tag -> yelow
+		color="rgb(252, 233, 77)" #tag -> yellow
 	fi
 }
 
@@ -270,8 +269,8 @@ processEdge() {
 # Finds the two endpoints of the edge
 # Arguments: 
 # $1 - delta x of first direction, $2 - delta y of first direction,
-# $3 - delta x of oposite direction, $4 - delta y of oposite direction
-# $5 - the character reptesenting the edge
+# $3 - delta x of opposite direction, $4 - delta y of opposite direction
+# $5 - the character representing the edge
 findEdgesEndpoints() {
 	connectToX="$x"; connectToY="$y"
 	findEdgesEndpoint "$1" "$2" "$5"
@@ -287,7 +286,7 @@ findEdgesEndpoints() {
 
 # Finds the endpoint in the specified direction
 # $1 - delta x of direction, $2 - delta y of direction,
-# $3 - the character reptesenting the edge
+# $3 - the character representing the edge
 findEdgesEndpoint() {
 	let newX="$connectToX"+"$1"
 	let newY="$connectToY"+"$2"
@@ -364,7 +363,7 @@ main() {
 	copyLinesIntoArray "$FILE_NAME"
 	calculateCanvasSize
 
-	# Drawing instructions for the imagemagic
+	# Drawing instructions for the ImageMagick
 	instructions=""
 
 	if [[ "$DEBUG" == "true" ]]; then
